#!/bin/bash
#Copy this file to 'credentials' in the same directory.
#Replace the examples with your actual credentials

#Your Postgres creds should go here.
export POSTGRES_HOST=12.34.56.78
export POSTGRES_USER=postgres
export POSTGRES_PASS=postgres
export POSTGRES_PORT=5432

#You only need to set these if you're using SMTP to send mail. Otherwise leave them commented.
export SMTP_HOST=smtp.example.com
export SMTP_PORT=587
export SMTP_DOMAIN=yourdomain
export SMTP_USER=user@example.com
export SMTP_PASS=password
export SMTP_AUTH=plain
export SMTP_TLSAUTO=true # i have no idea what this does but its default
